disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_newline
  - trailing_whitespace
  - function_body_length
  - function_parameter_count
included: # paths to include during linting. `--path` is ignored if present.
  - Example
identifier_name:
  min_length: 1